COMPILER = clang++

FLAGS = --std=c++98 -Wall -Wextra -Werror


vector:
	@$(COMPILER) $(FLAGS)	vector_tests.cpp -o vector.out 

map:
	@$(COMPILER) $(FLAGS)	map_tests.cpp -o map.out 

stack:
	@$(COMPILER) $(FLAGS)	stack_tests.cpp -o stack.out 
 
clean:
	rm -f vector.out map.out stack.out set.out